name:                webby
version:             1.0.1
synopsis:            A super-simple web server framework
homepage:            "https://github.com/donatello/webby"
description: |
  A super-simple, easy to use web server framework inspired by
  Scotty. The goals of the project are: (1) Be easy to use (2) Allow
  graceful exception handling (3) Parse request parameters easily and
  in a typed manner.
license-file: LICENSE
category:            Web
maintainer:
  - aditya.mmy@gmail.com
  - krishnan.parthasarathi@gmail.com
git: "https://github.com/donatello/webby"
bug-reports: "https://github.com/donatello/webby/issues"

extra-source-files:
- README.md

ghc-options: -Wall

flags:
  dev:
    manual: true
    default: false

when:
  - condition: flag(dev)
    ghc-options: "-Wall -Werror"

dependencies:
  - aeson >= 1.4 && < 2.2
  - relude >= 0.7
  - name: base
    version: ">= 4.7 && < 5"
    mixin:
      - hiding (Prelude)
  - binary >= 0.8 && < 1
  - bytestring >= 0.10 && < 1
  - formatting >= 6.3.7 && < 7.2
  - http-api-data >= 0.4 && < 0.6
  - http-types >= 0.12 && < 0.13
  - resourcet >= 1.2 && < 1.3
  - text >= 1.2 && < 2.1
  - unliftio >= 0.2.13 && < 0.3
  - unliftio-core >= 0.2 && < 0.3
  - unordered-containers >= 0.2.9 && < 0.3
  - wai >= 3.2 && < 3.3

source-dirs:
  - src

library:
  exposed-modules:
    - Webby
  generated-other-modules:
    - Paths_webby

default-extensions:
  - FlexibleInstances
  - MultiParamTypeClasses
  - MultiWayIf
  - NoImplicitPrelude
  - OverloadedStrings
  - ScopedTypeVariables
  - TupleSections

tests:
  webby-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - webby
    - tasty
    - tasty-hunit
    - tasty-quickcheck
