name:                webby
version:             0.1.2
synopsis:            A super-simple web server framework
description: |
  A super-simple, easy to use web server framework inspired by
  Scotty. The goals of the project are: (1) Be easy to use (2) Allow
  graceful exception handling (3) Parse request parameters easily and
  in a typed manner.
license-file: LICENSE
category:            Web
maintainer: aditya.mmy@gmail.com
extra-source-files:
- README.md

ghc-options: -Wall

flags:
  dev:
    manual: true
    default: false

when:
  - condition: flag(dev)
    ghc-options: -Werror

dependencies:
  - aeson >= 1.2 && < 1.5
  - base >= 4.7 && < 5
  - binary >= 0.8 && < 0.9
  - bytestring >= 0.10 && < 0.11
  - fast-logger >= 2.4 && < 2.5
  - formatting >= 6.3 && < 6.4
  - http-api-data >= 0.3 && < 0.5
  - http-types >= 0.12 && < 0.13
  - monad-logger >= 0.3 && < 0.4
  - protolude >= 0.2 && < 0.3
  - resourcet >= 1.2 && < 1.3
  - text >= 1.2 && < 1.3
  - unliftio >= 0.2.7 && < 0.3
  - unordered-containers >= 0.2.9 && < 0.3
  - wai >= 3.2 && < 3.3

source-dirs:
  - src

library:
  exposed-modules:
    - Webby

default-extensions:
  - FlexibleInstances
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - OverloadedStrings
  - ScopedTypeVariables
  - TupleSections

tests:
  webby-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - webby
    - tasty
    - tasty-hunit
    - tasty-quickcheck
