name: Haskell CI

on: [push]

jobs:
  build:
   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Haskell Tools
    - run: curl -sSL https://get.haskellstack.org/ | sh
    - name: Build library
      run: stack build
    - name: Run Tests
      run: stack test
