name: Haskell CI

# This ensures that previous jobs for the PR are canceled when the PR is
# updated.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.4', '8.6', '8.8', '8.10', '9.0', '9.2']
        cabal: ['latest']
        os: [ubuntu-latest, macOS-latest, windows-latest]
        exclude:
          # Appears to be buggy to build in windows
          - ghc: '8.8'
            os: 'windows-latest'
          - ghc: '8.10'
            os: 'windows-latest'

    steps:
    - uses: actions/checkout@v3
    - uses: haskell/actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
      uses: actions/cache@v3
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
          ~\AppData\Roaming\cabal\packages
          ~\AppData\Roaming\cabal\store
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}
        restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-

    - name: Install dependencies
      run: |
        cabal v2-update
        cabal v2-build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks -fexamples all
    - name: Run tests
      run: cabal test all
